version: 2

jobs:
  build:
    working_directory: ~/mpm

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      ANDROID_HOME: /opt/android/sdk
      ANDROID_BUILD_TOOLS: 27.0.3

    steps:
      - checkout

      # Restore cached dependencies (if any)
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "material-popup-menu/build.gradle" }}-{{ checksum  "sample/build.gradle" }}

      # Prepare the container for the build
      - run:
          name: Accept Android SDK license
          command: .circleci/ci-scripts/accept-android-licenses.sh
      - run:
          name: Ensure Android SDK install is up-to-date
          command: .circleci/ci-scripts/ensure-sdkmanager.sh

      # Create dummy local.properties file
      - run:
          name: Create local.properties
          command: printf 'bintray.user=dummy_user\nbintray.apikey=dummy_api_key' > local.properties

      # Run the main job command, delegating to Gradle
      - run:
          name: Run Gradle :check command
          command: ./gradlew check publishToMavenLocal --continue --no-daemon --stacktrace

      # Store all the downloaded dependencies in the CI cache
      - save_cache:
          paths:
            # Android SDK
            - /usr/local/android-sdk-linux/tools
            - /usr/local/android-sdk-linux/platform-tools
            - /usr/local/android-sdk-linux/build-tools
            - /usr/local/android-sdk-linux/licenses
            - /usr/local/android-sdk-linux/extras/google/m2repository

            # Gradle dependencies
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "material-popup-menu/build.gradle" }}-{{ checksum  "sample/build.gradle" }}

      # Collect static analysis reports as build artifacts
      - store_artifacts:
          path: material-popup-menu/build/reports
          destination: library-reports
      - store_artifacts:
          path: sample/build/reports
          destination: sample-reports

      # Collect JUnit test results
      - store_test_results:
          path: material-popup-menu/build/test-results/testDebugUnitTest
